import fs from 'fs';
import path from 'path';
const home = process.env.USERPROFILE || process.env.HOME;
const bak = path.join(home, '.codebuddy', 'models.json.bak-20260628');
const cfg = JSON.parse(fs.readFileSync(bak,'utf8'));
const m = cfg.models.find(x=>x.id==='deepseek-v4-pro');
const t0=Date.now();
const r = await fetch(m.url,{method:'POST',headers:{'Authorization':'Bearer '+m.apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:m.id,messages:[{role:'user',content:'中国的首都是哪个城市？只回答城市名，不要解释'}],max_tokens:256,temperature:0.3})});
const d = await r.json();
const c = d.choices?.[0]?.message;
console.log('status',r.status,'耗时',Date.now()-t0,'ms');
console.log('content:', JSON.stringify(c?.content));
console.log('reasoning_len:', (c?.reasoning_content||'').length);