// ecosystem.config.cjs — PM2 进程配置（巨量引擎监控全家桶）
// 用法: pm2 start ecosystem.config.cjs
//       pm2 start ecosystem.config.cjs --only pm2-5min   (仅启动5分钟)
//       pm2 start ecosystem.config.cjs --only pm2-15min  (仅启动15分钟)
const MONITOR_DIR = process.env.MONITOR_DIR || __dirname;
const LOG_DIR = `${MONITOR_DIR}\\monitor-data`;
const NODE = process.env.NODE_EXE || "C:\\Users\\HTF2026\\.workbuddy\\binaries\\node\\versions\\22.22.2\\node.exe";

module.exports = {
  apps: [
    // ====== 换班推送 常驻守护 ======
    {
      name: "shift-pusher",
      script: "src/services/shift-pusher-cli.mjs",
      cwd: MONITOR_DIR,
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "300M",
      out_file: `${LOG_DIR}\\pm2-shift-out.log`,
      error_file: `${LOG_DIR}\\pm2-shift-err.log`,
      merge_logs: true,
      time: true,
      cron_restart: "0 6 * * *",
    },

    // ====== 飞书群消息监听 常驻 (轮询模式，每10s拉取群消息) ======
    {
      name: "feishu-listener",
      script: "src/services/feishu-listener-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "200M",
      out_file: `${LOG_DIR}\\pm2-feishu-listener-out.log`,
      error_file: `${LOG_DIR}\\pm2-feishu-listener-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== feedback-server
    // ====== 直播状态监听 常驻 (每60s轮询，跟踪开播/下播，触发日汇总) ======
    {
      name: "live-watcher",
      script: "src/services/live-watcher-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      out_file: `${LOG_DIR}\\pm2-live-watcher-out.log`,
      error_file: `${LOG_DIR}\\pm2-live-watcher-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== feedback-server 常驻 HTTP 服务 (端口 8899, Dashboard 依赖) ======
    {
      name: "feedback-server",
      script: "src/services/http-server-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
      max_memory_restart: "200M",
      out_file: `${LOG_DIR}\\pm2-feedback-out.log`,
      error_file: `${LOG_DIR}\\pm2-feedback-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== 5分钟速报（cron 触发，跑完即退）======
    {
      name: "pm2-5min",
      script: "src/services/monitor-5min-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: false,
      max_restarts: 100,
      kill_timeout: 30000,
      cron_restart: "*/5 * * * *",
      out_file: `${LOG_DIR}\\pm2-5min-out.log`,
      error_file: `${LOG_DIR}\\pm2-5min-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== 15分钟监控（cron 触发，跑完即退）======
    {
      name: "pm2-15min",
      script: "src/services/monitor-15min-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: false,
      max_restarts: 100,
      kill_timeout: 60000,
      cron_restart: "*/15 * * * *",
      out_file: `${LOG_DIR}\\pm2-15min-out.log`,
      error_file: `${LOG_DIR}\\pm2-15min-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== 日报 23:05（cron 触发，跑完即退）======
    {
      name: "pm2-daily-report",
      script: "src/services/cron-daily-report-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { OEC_SILENT: "1", NODE_ENV: "production" },
      instances: 1,
      autorestart: false,
      max_restarts: 0,
      kill_timeout: 300000,
      cron_restart: "5 23 * * *",
      out_file: `${LOG_DIR}\\pm2-daily-report-out.log`,
      error_file: `${LOG_DIR}\\pm2-daily-report-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== AI区域号汇总 21:30（cron 触发，跑完即退）======
    {
      name: "pm2-ai-regions",
      script: "src/services/cron-ai-regions-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { OEC_SILENT: "1", NODE_ENV: "production" },
      instances: 1,
      autorestart: false,
      max_restarts: 0,
      kill_timeout: 120000,
      cron_restart: "30 21 * * *",
      out_file: `${LOG_DIR}\\pm2-ai-regions-out.log`,
      error_file: `${LOG_DIR}\\pm2-ai-regions-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== action-queue-worker 常驻 (watch模式，每15s轮询操作队列) ======
    {
      name: "action-queue-worker",
      script: "src/services/action-worker-cli.mjs",
      args: "--watch",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      // [v1.1] 必须单实例：文件锁 wx 标志依赖单进程互斥；容器化时需升级为 Redis 锁
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "200M",
      out_file: `${LOG_DIR}\\pm2-worker-out.log`,
      error_file: `${LOG_DIR}\\pm2-worker-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== Chrome 9222 守护（常驻，每60s探活，崩溃自动拉起）======
    {
      name: "chrome-guard",
      script: "src/cdp/guard.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      out_file: `${LOG_DIR}\\pm2-chrome-guard-out.log`,
      error_file: `${LOG_DIR}\\pm2-chrome-guard-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== 次日排班同步 23:00（每日提前缓存次日主播排班）======
    {
      name: "pm2-sync-tomorrow",
      script: "src/services/cron-sync-shifts-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { NODE_ENV: "production" },
      instances: 1,
      autorestart: false,
      max_restarts: 0,
      kill_timeout: 30000,
      cron_restart: "0 23 * * *",
      out_file: `${LOG_DIR}\\pm2-sync-tomorrow-out.log`,
      error_file: `${LOG_DIR}\\pm2-sync-tomorrow-err.log`,
      merge_logs: true,
      time: true,
    },

    // ====== 日汇总 23:35（全天数据核对后推送）======
    {
      name: "pm2-daily-summary",
      script: "src/services/cron-daily-summary-cli.mjs",
      cwd: MONITOR_DIR,
      exec_mode: "fork",
      interpreter: NODE,
      env: { OEC_SILENT: "1", NODE_ENV: "production", DAILY_SUMMARY_FALLBACK: "1" },
      instances: 1,
      autorestart: false,
      max_restarts: 0,
      kill_timeout: 120000,
      cron_restart: "35 23 * * *",
      out_file: `${LOG_DIR}\\pm2-daily-summary-out.log`,
      error_file: `${LOG_DIR}\\pm2-daily-summary-err.log`,
      merge_logs: true,
      time: true,
    },
  ],
};
